/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maquinaria;

import javax.swing.JOptionPane;

/**
 *
 * @author eblanco
 */
public class Interfaz extends javax.swing.JFrame {
Maquina excavadora,motoniveladora,cisterna,volqueta,montacargas,compactadora,tractor,grua,camion,cargadora;
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        excavadora=new Maquina();
        motoniveladora=new Maquina();
        cisterna=new Maquina();
        volqueta=new Maquina();
        montacargas=new Maquina();
        compactadora=new Maquina();
        tractor=new Maquina();
        grua=new Maquina();
        camion=new Maquina();
        cargadora=new Maquina();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bExcavadora = new javax.swing.JButton();
        bMotoniveladora = new javax.swing.JButton();
        bCisterna = new javax.swing.JButton();
        bVolqueta = new javax.swing.JButton();
        bMontaCargas = new javax.swing.JButton();
        bCompactadora = new javax.swing.JButton();
        bTractor = new javax.swing.JButton();
        bGrua = new javax.swing.JButton();
        bFurgon = new javax.swing.JButton();
        bCargadora = new javax.swing.JButton();
        bResultados = new javax.swing.JButton();
        bExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAQUINARIA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("ALQUILER DE MÁQUINAS");

        bExcavadora.setIcon(new javax.swing.ImageIcon("C:\\Users\\eblan\\Documents\\NetBeansProjects\\Maquinaria\\img\\excavadora-CX210B.png")); // NOI18N
        bExcavadora.setToolTipText("EXCAVADORA");
        bExcavadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcavadoraActionPerformed(evt);
            }
        });

        bMotoniveladora.setIcon(new javax.swing.ImageIcon("C:\\Users\\eblan\\Documents\\NetBeansProjects\\Maquinaria\\img\\motoniveladora.jpg")); // NOI18N
        bMotoniveladora.setToolTipText("MOTONIVELADORA");
        bMotoniveladora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMotoniveladoraActionPerformed(evt);
            }
        });

        bCisterna.setIcon(new javax.swing.ImageIcon("C:\\Users\\eblan\\Documents\\NetBeansProjects\\Maquinaria\\img\\cisterna.png")); // NOI18N
        bCisterna.setToolTipText(" CISTERNA DE AGUA");
        bCisterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCisternaActionPerformed(evt);
            }
        });

        bVolqueta.setIcon(new javax.swing.ImageIcon("C:\\Users\\eblan\\Documents\\NetBeansProjects\\Maquinaria\\img\\volqueta.png")); // NOI18N
        bVolqueta.setToolTipText("VOLQUETA");
        bVolqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolquetaActionPerformed(evt);
            }
        });

        bMontaCargas.setIcon(new javax.swing.ImageIcon("C:\\Users\\eblan\\Documents\\NetBeansProjects\\Maquinaria\\img\\montacargas.png")); // NOI18N
        bMontaCargas.setToolTipText("MONTACARGAS");
        bMontaCargas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMontaCargasActionPerformed(evt);
            }
        });

        bCompactadora.setIcon(new javax.swing.ImageIcon("C:\\Users\\eblan\\Documents\\NetBeansProjects\\Maquinaria\\img\\compactadora.png")); // NOI18N
        bCompactadora.setToolTipText("COMPACTADORA");
        bCompactadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCompactadoraActionPerformed(evt);
            }
        });

        bTractor.setIcon(new javax.swing.ImageIcon("C:\\Users\\eblan\\Documents\\NetBeansProjects\\Maquinaria\\img\\tractor.png")); // NOI18N
        bTractor.setToolTipText("TRACTOR");
        bTractor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTractorActionPerformed(evt);
            }
        });

        bGrua.setIcon(new javax.swing.ImageIcon("C:\\Users\\eblan\\Documents\\NetBeansProjects\\Maquinaria\\img\\gruas.png")); // NOI18N
        bGrua.setToolTipText("GRÚA");
        bGrua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGruaActionPerformed(evt);
            }
        });

        bFurgon.setIcon(new javax.swing.ImageIcon("C:\\Users\\eblan\\Documents\\NetBeansProjects\\Maquinaria\\img\\furgon.png")); // NOI18N
        bFurgon.setToolTipText("FURGÓN");
        bFurgon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFurgonActionPerformed(evt);
            }
        });

        bCargadora.setIcon(new javax.swing.ImageIcon("C:\\Users\\eblan\\Documents\\NetBeansProjects\\Maquinaria\\img\\cargadora.png")); // NOI18N
        bCargadora.setToolTipText("CARGADORA");
        bCargadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCargadoraActionPerformed(evt);
            }
        });

        bResultados.setBackground(new java.awt.Color(0, 102, 153));
        bResultados.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        bResultados.setForeground(new java.awt.Color(255, 255, 255));
        bResultados.setText("RESULTADOS");
        bResultados.setToolTipText("CALCULAR");
        bResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResultadosActionPerformed(evt);
            }
        });

        bExit.setBackground(new java.awt.Color(204, 51, 0));
        bExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\eblan\\Documents\\NetBeansProjects\\Maquinaria\\img\\exit.png")); // NOI18N
        bExit.setToolTipText("SALIR");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bExcavadora, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bMotoniveladora, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bCisterna, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bMontaCargas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(bCompactadora, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bTractor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bVolqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bGrua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bFurgon, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCargadora, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(bResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bExcavadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bMotoniveladora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCisterna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bVolqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bTractor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bGrua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bCompactadora, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bMontaCargas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bFurgon, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(bCargadora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(bExit)))
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExcavadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcavadoraActionPerformed
        if (nExcavadoras>0) {
            int priceHr=130000;
        int tiempo=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de Horas:"));   
            excavadora.calcularPrecio(priceHr, tiempo);
            nExcavadoras--;resExcavadoras++;contador++;
            JOptionPane.showMessageDialog(null, "El promedio por las maquinas alquiladas es de: "+excavadora.calcularPromedioDia(contador));
            
        } else {
            JOptionPane.showMessageDialog(null,"No hay más disponibles");
        }
        
       JOptionPane.showMessageDialog(null,"Se han alquilado: "+resExcavadoras+" Quedan por alquilar: "+nExcavadoras);
        
    }//GEN-LAST:event_bExcavadoraActionPerformed

    private void bMotoniveladoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMotoniveladoraActionPerformed
         if (nMotos>0) {
            int priceHr=165000;
        int tiempo=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de Horas:"));   
            motoniveladora.calcularPrecio(priceHr, tiempo);
            nMotos--;resMotos++;contador++;
            JOptionPane.showMessageDialog(null, "El promedio por las maquinas alquiladas es de: "+motoniveladora.calcularPromedioDia(contador));
            
        } else {
            JOptionPane.showMessageDialog(null,"No hay más disponibles");
        }
        
       JOptionPane.showMessageDialog(null,"Se han alquilado: "+resMotos+" Quedan por alquilar: "+nMotos);
    }//GEN-LAST:event_bMotoniveladoraActionPerformed

    private void bCisternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCisternaActionPerformed
        if (nCisternas>0) {
            int priceHr=98000;
        int tiempo=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de Horas:"));   
            cisterna.calcularPrecio(priceHr, tiempo);
            nCisternas--;resCisternas++;contador++;
            JOptionPane.showMessageDialog(null, "El promedio por las maquinas alquiladas es de: "+cisterna.calcularPromedioDia(contador));
            
        } else {
            JOptionPane.showMessageDialog(null,"No hay más disponibles");
        }
        
       JOptionPane.showMessageDialog(null,"Se han alquilado: "+resCisternas+" Quedan por alquilar: "+nCisternas);
    }//GEN-LAST:event_bCisternaActionPerformed

    private void bVolquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolquetaActionPerformed
       if (nVolquetas>0) {
            int priceHr=86500;
        int tiempo=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de Horas:"));   
            volqueta.calcularPrecio(priceHr, tiempo);
            nVolquetas--;resVolquetas++;contador++;
            JOptionPane.showMessageDialog(null, "El promedio por las maquinas alquiladas es de: "+volqueta.calcularPromedioDia(contador));
            
        } else {
            JOptionPane.showMessageDialog(null,"No hay más disponibles");
        }
        
       JOptionPane.showMessageDialog(null,"Se han alquilado: "+resVolquetas+" Quedan por alquilar: "+nVolquetas);
    }//GEN-LAST:event_bVolquetaActionPerformed

    private void bMontaCargasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMontaCargasActionPerformed
        if (nMontacargas>0) {
            int priceHr=44000;
        int tiempo=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de Horas:"));   
            montacargas.calcularPrecio(priceHr, tiempo);
            nMontacargas--;resMontacargas++;contador++;
            JOptionPane.showMessageDialog(null, "El promedio por las maquinas alquiladas es de: "+montacargas.calcularPromedioDia(contador));
            
        } else {
            JOptionPane.showMessageDialog(null,"No hay más disponibles");
        }
        
       JOptionPane.showMessageDialog(null,"Se han alquilado: "+resMontacargas+" Quedan por alquilar: "+nMontacargas);
    }//GEN-LAST:event_bMontaCargasActionPerformed

    private void bCompactadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCompactadoraActionPerformed
        if (nCompactadoras>0) {
            int priceHr=125000;
        int tiempo=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de Horas:"));   
            compactadora.calcularPrecio(priceHr, tiempo);
            nCompactadoras--;resCompactadoras++;contador++;
            JOptionPane.showMessageDialog(null, "El promedio por las maquinas alquiladas es de: "+compactadora.calcularPromedioDia(contador));
            
        } else {
            JOptionPane.showMessageDialog(null,"No hay más disponibles");
        }
        
       JOptionPane.showMessageDialog(null,"Se han alquilado: "+resCompactadoras+" Quedan por alquilar: "+nCompactadoras);
    }//GEN-LAST:event_bCompactadoraActionPerformed

    private void bTractorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTractorActionPerformed
        if (nTractores>0) {
            int priceHr=65700;
        int tiempo=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de Horas:"));   
            tractor.calcularPrecio(priceHr, tiempo);
            nTractores--;resTractores++;contador++;
            JOptionPane.showMessageDialog(null, "El promedio por las maquinas alquiladas es de: "+tractor.calcularPromedioDia(contador));
            
        } else {
            JOptionPane.showMessageDialog(null,"No hay más disponibles");
        }
        
       JOptionPane.showMessageDialog(null,"Se han alquilado: "+resTractores+" Quedan por alquilar: "+nTractores);
    }//GEN-LAST:event_bTractorActionPerformed

    private void bGruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGruaActionPerformed
        if (nGruas>0) {
            int priceHr=78600;
        int tiempo=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de Horas:"));   
            grua.calcularPrecio(priceHr, tiempo);
            nGruas--;resGruas++;contador++;
            JOptionPane.showMessageDialog(null, "El promedio por las maquinas alquiladas es de: "+grua.calcularPromedioDia(contador));
            
        } else {
            JOptionPane.showMessageDialog(null,"No hay más disponibles");
        }
        
       JOptionPane.showMessageDialog(null,"Se han alquilado: "+resGruas+" Quedan por alquilar: "+nGruas);
    }//GEN-LAST:event_bGruaActionPerformed

    private void bFurgonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFurgonActionPerformed
        if (nCamiones>0) {
            int priceHr=69800;
        int tiempo=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de Horas:"));   
           camion.calcularPrecio(priceHr, tiempo);
            nCamiones--;resCamiones++;contador++;
            JOptionPane.showMessageDialog(null, "El promedio por las maquinas alquiladas es de: "+camion.calcularPromedioDia(contador));
            
        } else {
            JOptionPane.showMessageDialog(null,"No hay más disponibles");
        }
        
       JOptionPane.showMessageDialog(null,"Se han alquilado: "+resCamiones+" Quedan por alquilar: "+nCamiones);
    }//GEN-LAST:event_bFurgonActionPerformed

    private void bCargadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCargadoraActionPerformed
        if (nCargadoras>0) {
            int priceHr=105000;
        int tiempo=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de Horas:"));   
            cargadora.calcularPrecio(priceHr, tiempo);
            nCargadoras--;resCargadoras++;contador++;
            JOptionPane.showMessageDialog(null, "El promedio por las maquinas alquiladas es de: "+cargadora.calcularPromedioDia(contador));
            
        } else {
            JOptionPane.showMessageDialog(null,"No hay más disponibles");
        }
        
       JOptionPane.showMessageDialog(null,"Se han alquilado: "+resCargadoras+" Quedan por alquilar: "+nCargadoras);
    }//GEN-LAST:event_bCargadoraActionPerformed

    private void bResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResultadosActionPerformed
        JOptionPane.showMessageDialog(null,"Máquinas alquiladas Hoy: "+contador);
        JOptionPane.showMessageDialog(null,"Lista de Maquinas Alquiladas:\n "+
                "Excavadoras: "+resExcavadoras+
                "\nMotoniveladoras: "+resMotos+
                "\nCisternas: "+resCisternas+
                "\nVolquetas: "+resVolquetas+
                "\nMontaCargas: "+resMontacargas+
                "\nCompactadoras: "+resCompactadoras+
                "\nTractores: "+resTractores+
                "\nGrúas: "+resGruas+
                "\nCamiones: "+resCamiones+
                "\nCargadoras: "+resCargadoras);
        
    }//GEN-LAST:event_bResultadosActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        System.exit(0);
            
    }//GEN-LAST:event_bExitActionPerformed

    
    
    public int getContador() {
        return contador;
    }

    public void setContador(int contador) {
        this.contador = contador;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
private int contador=0;
int nExcavadoras=5,resExcavadoras=0;
int nMotos=5,resMotos=0;
int nCisternas=5,resCisternas=0;
int nVolquetas=5,resVolquetas=0;
int nMontacargas=5,resMontacargas=0;
int nCompactadoras=5,resCompactadoras=0;
int nTractores=5,resTractores=0;
int nGruas=5,resGruas=0;
int nCamiones=5,resCamiones=0;
int nCargadoras=5,resCargadoras=0;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCargadora;
    private javax.swing.JButton bCisterna;
    private javax.swing.JButton bCompactadora;
    private javax.swing.JButton bExcavadora;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bFurgon;
    private javax.swing.JButton bGrua;
    private javax.swing.JButton bMontaCargas;
    private javax.swing.JButton bMotoniveladora;
    private javax.swing.JButton bResultados;
    private javax.swing.JButton bTractor;
    private javax.swing.JButton bVolqueta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
